import { Geist, Geist_Mono } from "next/font/google";
import { DM_Sans } from '@next/font/google';
import "./globals.css";
const geistSans = Geist({
  subsets: ["latin"], // Add this
  preload: true, // Keep preloading
  variable: "--font-geist-sans",  
});

const dmSans = DM_Sans({
  subsets: ['latin'], 
  weight: ['400', '500', '700'], 
  style: ['normal', 'italic'], 
  variable: "--font-dm-sans",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono", 
  subsets: ["latin"],
});

export const metadata = {
  title: "Good People Foundation",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={" "}
      >
        {children}
      </body>
    </html>
  );
}
